spring.application.name=tarea1-crud-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/tarea1_db
spring.datasource.username=tarea1_user
spring.datasource.password=tarea1_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=ZdMVxH2X5Kqe+SrbUO1YwWD/Y1Z6SS/CxOTYdBOukLU=
security.jwt.expiration-time=3600000
